name: build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        java: [
          17,
        ]
        os: [ ubuntu-22.04, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
